spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://148.70.16.82:3306/collectionutil_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gols852456mysql.
    hikari:
      jdbc-url: jdbc:mysql://148.70.16.82:3306/collectionutil_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: gols852456mysql.
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP